version: "2"

linters:
  default: all
  disable:
    - wsl
    - revive
    - depguard
    - funlen
    - cyclop
    - err113
    - forbidigo
    - gocognit
    - maintidx
    - gocyclo
    - exhaustruct
    - wrapcheck
    - funcorder
    - varnamelen
    - gomoddirectives
    - noinlineerr
    - mnd
    - ireturn
    - lll
    - goconst
    - nestif
    - interfacebloat
    - nonamedreturns
    - testpackage
    - paralleltest
    - gochecknoglobals
    - tagliatelle
    - nlreturn
    - grouper

  settings:
    gocritic:
      enable-all: true
      disabled-checks:
        - hugeParam

    tagliatelle:
      case:
        rules:
          json: snake

    goheader:
      values:
        const:
          COMPANY: Sumicare
      template: |-
        Copyright {{ YEAR }} {{ COMPANY }}

        Licensed under the Apache License, Version 2.0 (the "License");
        you may not use this file except in compliance with the License.
        You may obtain a copy of the License at

            http://www.apache.org/licenses/LICENSE-2.0

        Unless required by applicable law or agreed to in writing, software
        distributed under the License is distributed on an "AS IS" BASIS,
        WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
        See the License for the specific language governing permissions and
        limitations under the License.

    gomoddirectives:
      replace-local: true
      exclude-forbidden: true
      ignore-forbidden: true
      toolchain-forbidden: true
      toolchain-pattern: 'go1\.25\.\d+$'
      tool-forbidden: true
      go-debug-forbidden: true
      go-version-pattern: '\d\.\d+(\.\d+)?'

    gosec:
      concurrency: 12

      config:
        global:
          nosec: true
          show-ignored: true
          audit: true
        G101:
          pattern: "(?i)passwd|pass|password|pwd|secret|token|pw|apiKey|bearer|cred"
          ignore_entropy: false
          entropy_threshold: "80.0"
          per_char_threshold: "3.0"
          truncate: "32"
        G104:
          fmt:
            - Fscanf
        G111:
          pattern: "http\\.Dir\\(\\\"\\/\\\"\\)|http\\.Dir\\('\\/'\\)"
        G301: "0750"
        G302: "0600"
        G306: "0600"

    gosmopolitan:
      watch-for-scripts:
        - Devanagari
        - Han
        - Hangul
        - Hiragana
        - Katakana

    govet:
      enable-all: true
      settings:
        shadow:
          strict: true

    grouper:
      const-require-single-const: true
      const-require-grouping: false

      import-require-single-import: true
      import-require-grouping: true

      type-require-single-type: true
      type-require-grouping: false

      var-require-single-var: true
      var-require-grouping: true

    iface:
      enable:
        - identical
        - unused
        - opaque
        - unexported

    inamedparam:
      skip-single-param: true

    ineffassign:
      check-escaping-errors: true

    interfacebloat:
      max: 8

    iotamixing:
      report-individual: true

    ireturn:
      allow: [anon, error, empty, stdlib, generic]

    lll:
      line-length: 180
      tab-width: 2

    loggercheck:
      slog: true

  exclusions:
    generated: strict
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo

issues:
  max-issues-per-linter: 0
  max-same-issues: 50
  uniq-by-line: true
  fix: true

output:
  formats:
    text:
      colors: true
      print-issued-lines: false

  path-mode: "abs"

  sort-order:
    - linter
    - severity
    - file

  show-stats: false

run:
  timeout: 1m
  allow-parallel-runners: true
  allow-serial-runners: true
  go: "1.26"
  concurrency: 32

severity:
  default: error
